#!/bin/bash


for file in regular/*.c; do
  if ./semchecker $file; then
    echo "$file: OK"
  else
    echo "$file: NG"
    exit -1
  fi
done

for file in semerror/*.c; do
  if ./semchecker $file; then
    echo "$file: NG"
    exit -1
  else
    echo "$file: OK"
  fi
done

